spring:
  application:
    name: airline-server
  datasource:
    url: jdbc:mysql://localhost:3306/airline_server?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#        mail:
#          host: smtp.gmail.com
#          port: 587
#          username: stackflowover3@gmail.com
#          password: fodh vqes baje dkst
#          protocol: smtp
#          properties:
#                mail:
#                  smtp:
#                    auth: true
#                    starttls:
#                      enable: true
#                logging:
#                  level:
#                    org.springframework.mail: DEBUG


server:
  servlet:
    context-path: /api/v1/


